### ISSUE TITLE
Crash after searching

### ISSUE THREAD

**Issue by aeldemery** [misterdanb/shady#119]
I've compiled `shady` form source. After running it and searching for any term, the program crashes.
Here is the backtrace

```
Core was generated by `shady'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f804f11944d in ?? () from /usr/lib/dri/nouveau_dri.so
[Current thread is 1 (Thread 0x7f807f8c4980 (LWP 27563))]
(gdb) bt -full
#0  0x00007f804f11944d in  () at /usr/lib/dri/nouveau_dri.so
#1  0x00007f804f126209 in  () at /usr/lib/dri/nouveau_dri.so
#2  0x00007f804f12b218 in  () at /usr/lib/dri/nouveau_dri.so
#3  0x00007f804e9ea3b9 in  () at /usr/lib/dri/nouveau_dri.so
#4  0x00007f804e9ea450 in  () at /usr/lib/dri/nouveau_dri.so
#5  0x0000561205ff0ba8 in shady_core_shader_compiler_dummy_render_glPython Exception <class 'ValueError'> Variable 'static_fundamental_type_nodes' not found.: 
 (buf_prop=)
    at ../src/core/shader_compiler.vala:538
        __func__ = "shady_core_shader_compiler_dummy_render_gl"
#6  0x0000561205fec82d in shady_core_shader_compiler_compilePython Exception <class 'ValueError'> Variable 'static_fundamental_type_nodes' not found.: 
 (data=) at ../src/core/shader_compiler.vala:127
Python Exception <class 'ValueError'> Variable 'static_fundamental_type_nodes' not found.: 
        _tmp10_ = 
Python Exception <class 'ValueError'> Variable 'static_fundamental_type_nodes' not found.: 
        _tmp9_ = 
Python Exception <class 'ValueError'> Variable 'static_fundamental_type_nodes' not found.: 
        buf_prop = 
        buf_prop_collection = 0x561208d94ef0
        buf_prop_collection_length1 = 1
        _buf_prop_collection_size_ = 0
        buf_prop_it = 0
Python Exception <class 'ValueError'> Variable 'static_fundamental_type_nodes' not found.: 
        _tmp5_ = 
        _tmp7_ = 0x561208d94ef0
        _buf_props_size_ = 1
        buf_props = 0x561208d94ef0
        _tmp6_ = 1
        buf_props_length1 = 1
        _tmp8_ = 0x561208d94ef0
        _tmp8__length1 = 1
        _data1_ = 0x7f7ff8001b70
Python Exception <class 'ValueError'> Variable 'static_fundamental_type_nodes' not found.: 
        _tmp0_ = 
        _tmp1_ = 0x7f7fbc007870
        success = 1
Python Exception <class 'ValueError'> Variable 'static_fundamental_type_nodes' not found.: 
        _tmp2_ = 
--Type <RET> for more, q to quit, c to continue without paging--
```

I've NVIDIA card with open source driver.

**Comment by aeldemery** [comment]
switching to closed source nvidia drivers and X11 didn't help. It is still crashes with a different message and backtrace

```
Gdk-Message: 10:14:52.047: org.hasi.shady: Fatal IO error 11 (Resource temporarily unavailable) on X server :0.
```

```
Core was generated by `shady'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007f44b9e22615 in raise () from /usr/lib/libc.so.6
[Current thread is 1 (Thread 0x7f44b6e62980 (LWP 12698))]
(gdb) bt -full
#0  0x00007f44b9e22615 in raise () at /usr/lib/libc.so.6
#1  0x00007f44b9e0b862 in abort () at /usr/lib/libc.so.6
#2  0x00007f44b9e0b747 in _nl_load_domain.cold () at /usr/lib/libc.so.6
#3  0x00007f44b9e1abf6 in  () at /usr/lib/libc.so.6
#4  0x00007f44b9849c49 in  () at /usr/lib/libX11.so.6
#5  0x00007f44b9849cee in  () at /usr/lib/libX11.so.6
#6  0x00007f44b9849fe2 in _XEventsQueued () at /usr/lib/libX11.so.6
#7  0x00007f44b983b992 in XPending () at /usr/lib/libX11.so.6
#8  0x00007f44bb2eaae0 in  () at /usr/lib/libgdk-3.so.0
#9  0x00007f44bbb54790 in g_main_context_prepare () at /usr/lib/libglib-2.0.so.0
#10 0x00007f44bbba60a6 in  () at /usr/lib/libglib-2.0.so.0
#11 0x00007f44bbb53421 in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#12 0x00007f44bb149d1e in g_application_run () at /usr/lib/libgio-2.0.so.0
#13 0x000056356cabf457 in _vala_main (args=0x7ffe8ff20c58, args_length1=1) at ../src/main.vala:29
        app = 0x56356e9bb1d0
        _tmp0_ = 0x56356e9bb1d0
        result = 0
#14 0x000056356cabf49a in main (argc=1, argv=0x7ffe8ff20c58) at ../src/main.vala:22
```

**Comment by heyjuvi** [comment]
Thanks for testing! Indeed we mostly test on Intel gpus with mesa driver, so this is most likely connected to some difference with nvidia gpus.

Can you please provide the driver version and gpu you have tested with?
Do you always get the same backtraces or does it change from time to time?

**Comment by Ninja-Koala** [comment]
I also tested on AMD with mesa, but not NVIDIA yet.
It might well be that it's just an OpenGL extension missing or something like that, because i'm not doing any OpenGL
error handling yet and i'm not even querying which extensions are supported.

**Comment by aeldemery** [comment]
Thank you for taking the time to solve this issue. As soon as I get a chance in the coming days I would report back the details of my test setup.
Thank you.

**Comment by Ninja-Koala** [comment]
I did a quick test on a PC with NVIDIA card and mesa driver and could reproduce this crash.
I will try to debug this once i have the time for it.
